# Home route

/home:
  controller: home
  action: index

# Installer routes

/installer:
  controller: Installer
  action: index

/installer/process:
  controller: Installer
  action: configDatabase

/installer/account:
  controller: Installer
  action: createAdmin

/installer/validate:
  controller: Security
  action: validate

/installer/login:
  controller: Security
  action: login

/installer/forgot-password:
  controller: Security
  action: forgotPassword

# dashboard routes

/dashboard/page-builder:
  controller: Dashboard
  action: index

/dashboard/page-builder/delete-page:
  controller: PageBuilder
  action: deletePage

/dashboard/page-builder/create-page:
  controller: dashboard
  action: index

/dashboard/template:
  controller: Dashboard
  action: index

/dashboard/comment :
  controller: Dashboard
  action: index

/dashboard/user:
  controller: Dashboard
  action: index

/dashboard/logout:
  controller: Security
  action: logout

/dashboard/update-password:
  controller: User
  action: changePassword

/dashboard/update-user:
  controller: User
  action: editUser
