
/home:
  controller: home
  action: index

/installer:
  controller: Installer
  action: index

/installer/process:
  controller: Installer
  action: configDatabase

/installer/account:
  controller: Installer
  action: createAdmin

/installer/login:
  controller: Installer
  action: login

/dashboard:
  controller: Dashboard
  action: index