# User

/home:
  controller: home
  action: index

/installer:
  controller: installer
  action: index

/installer/process:
  controller: installer
  action: configDatabase

/installer/account:
  controller: installer
  action: createAdmin